import Head from 'next/head'
import Image from 'next/image'

import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import MainLayout from '../components/MainLayout'
import Trades from '../components/Trades'
import Ticker from '../components/Ticker'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>React example with websocket</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />

        <MainLayout>
          <p className={styles.description}>
            Example of ws API on FTX using
            <code className={styles.code}>Next.js + react-use-websocket</code>
          </p>

          <div className={styles.grid}>
            <div className={styles.card}>
              <Trades />
            </div>

            <div className={styles.card}>
              <Ticker />
            </div>
          </div>
        </MainLayout>
      </main>
    </div>
  )
}
